### ISSUE TITLE
Symbolic Bound Tightening using Python API

### ISSUE THREAD

**Issue by darioguidotti** [NeuralNetworkVerification/Marabou#210]
Hello,

I am using Marabou to test some neural networks for targeted adversarial robustness
and I noticed that, when using the python API, apparently Marabou do not use
Symbolic Bound Tightening. I also noticed that the tool appears to behave differently
if it is used on the same problem from the command line or from the Python API:
in particular, it appears that when called from the API it does not print the statistics update
when it should and it always print "Number of tightened bounds: 0".

Even so, the final solutions appear to be coherent when applied to the same problem.

Could it be a bug in the printing of the statistics update? Or am I doing something wrong?

The code to reproduce the problem and the transcription of the results (in command_line_test.txt and python_api_test.txt) is in the following .zip.

[sbt_test.zip](https://github.com/NeuralNetworkVerification/Marabou/files/3968335/sbt_test.zip)

Thank you for your time!

**Comment by anwu1219** [comment]
Hi Dario, thanks for bringing up this question. Marabou currently does not support Symbolic Bound Tightening(SBT) when called through the python API. The reason is that SBT assumes the structure of a neural network (i.e., propagating bounds through layers) but the python API allows you to pose more general queries over linear real mathematics without assuming it's a query over a neural network.
But obviously this is a desirable feature when the query IS over a neural network, so we will add this to our to-do list.

**Comment by darioguidotti** [comment]
Ok, thank you very much for your response!
Cheers,
Dario
