### ISSUE TITLE
evaluateWithMarabou doesn't work with DNC

### ISSUE THREAD

**Issue by vbCrLf** [NeuralNetworkVerification/Marabou#330]
```
import numpy as np
from maraboupy import Marabou

NNET_FILE_NAME = "../Marabou/src/input_parsers/acas_example/ACASXU_run2a_1_1_tiny_2.nnet"
OPT = Marabou.createOptions(verbosity=100)
OPT_DNC = Marabou.createOptions(verbosity=100, dnc=True, numWorkers=8)

nn = Marabou.read_nnet(NNET_FILE_NAME)

print("Works")
nn.evaluate([[0, 1, 2, 3, 4, 5, 6, 7, 8 ,9]], options=OPT)

print("Doesn't work")
nn.evaluate([[0, 1, 2, 3, 4, 5, 6, 7, 8 ,9]], options=OPT_DNC)
```

`evaluateWithMarabou` doesn't work when using DNC. The code above reproduces the problem.
Using DNC for evaluation is an overkill, but it is easy to accidentally do when provide the same options for every call to Marabou, and it took me some time to find the problem.
I think it is enough to raise an exception when running evaluate with DNC, no need to fix it.

**Comment by kjulian3** [comment]
@anwu1219 can you take a look at this? It looks like evaluating with DNC mode returns only the input and output variable assignments, and the output variable numbers have changed from 105-109 to 5-9. Maybe because other variables were eliminated during pre-processing? MarabouCore in DNC mode uses the dncManager's getSolution method, which is a bit different than how non-DNC mode extracts the solution.

Also, DNC mode in maraboupy is currently not tested. It would be great to add a test file for DNC mode and include this script as one of the tests.

**Comment by anwu1219** [comment]
Hi, thanks for bringing up this issue! I created a PR(https://github.com/NeuralNetworkVerification/Marabou/pull/333) to fix this issue. Could you please try and see if it fixes your issue.

Andrew

**Comment by anwu1219** [comment]
> @anwu1219 can you take a look at this? It looks like evaluating with DNC mode returns only the input and output variable assignments, and the output variable numbers have changed from 105-109 to 5-9. Maybe because other variables were eliminated during pre-processing? MarabouCore in DNC mode uses the dncManager's getSolution method, which is a bit different than how non-DNC mode extracts the solution.
> 
> Also, DNC mode in maraboupy is currently not tested. It would be great to add a test file for DNC mode and include this script as one of the tests.

It is exactly this issue. The worker engines directly takes in a preprocessed InputQuery instead of preprocessing them individually. Therefore, the worker engine is unaware of the mapping from previous indices to the post-preprocessing indices. I created a PR and it'd be great if you could take a look.
I'll try add a test to DnC and submit a PR.

**Comment by vbCrLf** [comment]
@anwu1219 yep, the PR fixes the issue! Thanks 👍
