### ISSUE TITLE
Python API support for disjunction queries, please :)

### ISSUE THREAD

**Issue by grese** [NeuralNetworkVerification/Marabou#387]
# Requesting Python API support for Disjunction Queries

I'd like to request the ability to be able to create disjunction queries on inputs and outputs using the Python APIs. The request for disjunction queries on inputs stems from the need to support networks with categorical (one-hot encoded) features. The request for disjunction queries on outputs stems from the need to be able to create more complex queries for classifiers. Examples of both are shown below.

## Inputs Example - NN with OneHot Encoded Feature

_Consider a ficticious NN with 4 inputs:_ 
* Input `x0` accepts a floating point value.
* Inputs `x1`, `x2`, and `x3` represent a one-hot encoded feature.

Since inputs `x1`, `x2`, and `x3` are one-hot encoded, they will always be 0 or 1, and depend on each-other. For example, when `x1` is 1, `x2` and `x3` are always 0. Below are a few sample inputs to show the behavior.

_Sample Input (x1=1)_
```
x0: 0.123
x1: 1
x2: 0
x3: 0
```

_Sample Input (x2=1)_
```
x0: 0.234
x1: 0
x2: 1
x3: 0
```

_Sample Input (x3=1)_
```
x0: 0.345
x1: 0
x2: 0
x3: 1
```

It would be nice to encode these one-hot features with a disjunction query such as the one below. This currently isn't possible with the Python APIs.

_NOTE: I'm just using the prop file syntax here for brevity's sake. The request is to add this functionality to the Python APIs_

```
x0 >= 0.123
x0 <= 0.234
(
(x1==1 
 x2==0
 x3==0) 
or 
(x1==0
 x2==1
 x3==0)
or
(x1==0
 x2==0
 x3==1)
)
```

## Outputs Example - NN Classifier

_Consider a fictitious NN classifier with 1 input and 3 outputs:_ 

* Input `x0` is a floating point number.
* Outputs `y0`, `y1`, and `y2` represent outputs for 3 classes.

For example, let's consider that I want to prove that the predicted label is ALWAYS `y1` within a given region of the input space. I would want Marabou to return SAT only if some other label (`y0` or `y2`) can be predicted. Using the Python APIs, I currently have to make the following TWO queries to accomplish this, which isn't very performant and requires additional code.

_NOTE: I'm just using the prop file syntax here for brevity's sake. The request is to add this functionality to the Python APIs_

_Query 1:_
```
x0 >= 0.123
x0 <= 0.234
y1 -y0 <= 0
y2 -y0 <= 0
```

_Query 2:_
```
x0 >= 0.123
x0 <= 0.234
y0 -y2 <= 0
y1 -y2 <= 0
```

So, it would be nice to also have support for disjunction queries on the outputs such as the one below. Using the query below, I'd be able to prove that `y1` is always predicted with a single query (which currently isn't possible via the Python APIs).

```
x0 >= 0.123
x0 <= 0.234

(
(y1 -y0 <= 0
 y2 -y0 <= 0)
or 
(y0 -y2 <= 0
 y1 -y2 <= 0)
)
```

**Comment by guykatzz** [comment]
Hi John,
I see that Andrew volunteered to expose this interface - hopefully that should be pretty straightforward.

Still, as a general comment, disjunction constraints should be avoided as possible, because they are the most general kind of constraint and consequently do not support any clever deduction steps - so only use them if you really have to.

For your examples, for the one hot-encoding, it might be easier to break the query into n sub-queries for if you have n one-hot variables; and if you do use a disjunction, you can provide some helpful information to Marabou, such as \sum_{i=1}^n x_i = 1.

For output disjunctions, please have a look at Figure 3 in this paper: https://arxiv.org/pdf/1910.14574.pdf.

**Comment by grese** [comment]
@guykatzz - Thanks for the info! Just to clarify for my own understanding, do the disjunctions cause a hit on performance, or does it make the results less reliable? I'm unfamiliar the "deduction steps" 😄.

The suggestion you provided about breaking the one-hot into multiple queries makes sense. Our network has 2 one-hot encoded features with 5 categories each,  so I guess that means I'd need 25 separate queries to cover all of the bases.

**Comment by anwu1219** [comment]
Hi John, I created a PR (linked to this issue) that exposes disjunctions to the python API.
An example can be found at https://github.com/anwu1219/Marabou/blob/disj/maraboupy/examples/5_DisjunctionConstraintExample.py 

The PR review process might take some time but it'd be great if you could try on your benchmark to see if it works.

Guy's comment is more related to the performance than soundness (which shouldn't be affected), since we didn't have too much optimizations for disjunction constraints. 

To tell Marabou that the sum of the feature is one, you could add an equation constraint 
`  network.addEquality([v1,v2,v3,v4,v5], [1,1,1,1,1],[1])
`
, which translates to v1 + v2 + v3 + v4 + v5 = 1

Regarding adding output constraints using the way described in that paper. 
It can be done through the python API by adding new variables, equality constraints, and ReLU constriants, etc, using methods such as 
MarabouNetwork.getNewVariable()
MarabouNetwork.addRelu()
MarabouNetwork.addEquality()
...

We can chat more if it is unclear.

**Comment by grese** [comment]
@anwu1219 - Great. Thanks for the info. I'll keep an eye on the PR.

At a first glance, the examples make sense, but I'll let you know if I have any questions once I start using the APIs.
