### ISSUE TITLE
unsound UNSAT on MNIST

### ISSUE THREAD

**Issue by nhamlv-55** [NeuralNetworkVerification/Marabou#568]
Hello team,
I have tried the code and the network in this answer
https://github.com/NeuralNetworkVerification/Marabou/issues/494#issuecomment-1028319796
However, I still get UNSAT on all labels.
As a sanity check, I change eps to 1 (any pixel can be changed to any other pixel), but I still get UNSAT.
Please let me know if you can reproduce the issue.
I'm running the code at the commit 2641ce74ccf0ebb53345c4a0f6b4c773df40e8a4
Thanks a lot.

**Comment by idan0610** [comment]
The bug was caused by a numerical stability problem in the preprocess stage of the queries. To fix the bug, please update file src/configuration/GlobalConfiguration.cpp and change the value of the constant GlobalConfiguration::PREPROCESSOR_ALMOST_FIXED_THRESHOLD to a lower value. 
For example, replace the following line in GlobalConfiguration.cpp:

```
const double GlobalConfiguration::PREPROCESSOR_ALMOST_FIXED_THRESHOLD = 0.00001;
```

with:

```
const double GlobalConfiguration::PREPROCESSOR_ALMOST_FIXED_THRESHOLD = 0.0000000001;
```

This should solve the issue. Marabou finds an adversarial example for the given example, where the adversarial class is 3, as expected.
