### ISSUE TITLE
Bug: x = 0 gives error however x <= 0 returns SAT

### ISSUE THREAD

**Issue by ChaahatJain** [NeuralNetworkVerification/Marabou#602]
Hello, 

I am testing MarabouCore equations. 
Currently, I am checking if the following system of equations is satisfiable: 
   x = 0 or x = 1 
   x = 0
Running the following code returns an Index Error for line "vars = MarabouCore.solve( ...): 
`
    from maraboupy import MarabouCore
    from maraboupy.Marabou import createOptions

    inputQuery = MarabouCore.InputQuery()
    inputQuery.setNumberOfVariables(1)

    eq1 = MarabouCore.Equation(MarabouCore.Equation.EQ)
    eq1.addAddend(1, 0)
    eq1.setScalar(0)

    eq2 = MarabouCore.Equation(MarabouCore.Equation.EQ)
    eq2.addAddend(1, 0)
    eq2.setScalar(1)

    disjunction = [[eq1], [eq2]]
    MarabouCore.addDisjunctionConstraint(inputQuery, disjunction)

    eq3 = MarabouCore.Equation(MarabouCore.Equation.EQ)
    eq3.addAddend(1, 0)
    eq3.setScalar(0)
    inputQuery.addEquation(eq3)

    inputQuery.setLowerBound(0, 0)
    inputQuery.setUpperBound(0, 1)

    options = createOptions()
    vars = MarabouCore.solve(inputQuery, options, "")
    print(vars[0])
`

However, replacing eq3 from x = 0 to x <= 0 returns SAT. 

This seems like very strange behaviour. 
Would someone be able to provide some intuition regarding this?

**Comment by ChaahatJain** [comment]
A simpler reproducible test is provided below: 
`
    inputQuery = MarabouCore.InputQuery()
    inputQuery.setNumberOfVariables(1)

    eq = MarabouCore.Equation(MarabouCore.Equation.EQ)
    eq.addAddend(1, 0)
    eq.setScalar(0)
    inputQuery.addEquation(eq)

    inputQuery.setLowerBound(0, 0)
    inputQuery.setUpperBound(0, 1)

    options = createOptions()
    vars = MarabouCore.solve(inputQuery, options, "")
    print(vars[0])
`
This outputs an error. However, changing MarabouCore.Equation.EQ to MarabouCore.Equation.LE returns SAT.

**Comment by anwu1219** [comment]
Hi @ChaahatJain , thanks for bringing this up! The culprit is most likely the DisjunctionConstraint, which is still experimental and not as thoroughly tested as other constraints. I would try avoiding using disjunction constraints (by manually checking each disjunct). 
I do have an idea of where the issue is, so I'll look into this at the mean time.

**Comment by anwu1219** [comment]
Ok, I created a PR to fix this. Your tests work now on the new branch.

**Comment by ChaahatJain** [comment]
Hi @anwu1219, thanks for fixing the issue. Since the second example posted does not use DisjunctionConstraints, I am not sure that it is the only problem here. Isn't there a problem with MarabouCore.Equation.EQ as well? 

Regarding manually checking each disjunct - 
I am currently working on modelling a transition system in Marabou which requires converting many (if p and q then r and s) rules. I have been approaching this by transforming the formula to (not p or not q or (r and s)) at the moment. Since there are many such rules, it would not be feasible for me to manually check each disjunct. Is there some functionality in MarabouCore that I am missing to deal with such problems?

**Comment by anwu1219** [comment]
Yes, the issue here is actually not the DisjunctionConstraint. Instead, the issue is that internally we are trying to reconstruct a neural network structure of the given constraints. And in the case when the input variables are not given, there is a corner case where the solver will crash. 

I see. In that case, probably DisjunctionConstraint is the way to go. I think the PR above and the previous one addressing your other issue should fix the main issue in the DisjunctionConstraint. If you continue seeing errors, please let me know.

**Comment by ChaahatJain** [comment]
Hi @anwu1219, 
[Constraint.txt](https://github.com/NeuralNetworkVerification/Marabou/files/10014832/Constraint.txt)
[SAT assignmnet.txt](https://github.com/NeuralNetworkVerification/Marabou/files/10014834/SAT.assignmnet.txt)

I have modelled a constraint using MarabouCore.disjunctionConstraint. This constraint is shown in Constraint.txt. The algorithm returns SAT with the assignment in SAT assignment.txt. 
However, on inspecting the constraint, it seems like everything is false. Could you have a look at it and let me know if I am missing anything?  

Thank you very much for your help with this.
