### ISSUE TITLE
Bug: DisjunctionConstraint with unit clause incorrect behaviour

### ISSUE THREAD

**Issue by ChaahatJain** [NeuralNetworkVerification/Marabou#607]
Hi @anwu1219, 

I have found another error in the disjunctionConstraint. If we run the code below using the commented lines, it returns UNSAT. 
However, if I add an equation using addDisjunctionConstraint, the code returns SAT which is strange. 
This problem persists even in the case where it is not a unit clause. For that, please have a look at my latest comment in Issue #602 with a complete example at the end. 
The minimal working example I am using is: 
```
from maraboupy import MarabouCore
from maraboupy.Marabou import createOptions

inputQuery = MarabouCore.InputQuery()
inputQuery.setNumberOfVariables(1)

eq0 = MarabouCore.Equation()
eq0.addAddend(1,0)
eq0.setScalar(1)


eq1 = MarabouCore.Equation(MarabouCore.Equation.EquationType.GE)
eq1.addAddend(-1, 0)
eq1.setScalar(0)
inputQuery.addEquation(eq0)

 # inputQuery.addEquation(eq1) - returns UNSAT which is correct
MarabouCore.addDisjunctionConstraint(inputQuery, [[eq1]]) # Returns SAT which is incorrect


inputQuery.setLowerBound(0,-1)
inputQuery.setUpperBound(0,1)

options = createOptions()
vars = MarabouCore.solve(inputQuery, options, "")
print(vars[0])
print(vars[1:])
```

**Comment by anwu1219** [comment]
Hi @ChaahatJain , thanks a lot for chasing down this error case. The issue is actually with the way we handle (in)equalities with only one variable. We try to turn that into a variable (to reduce overhead). However this conversion logic is buggy.  
The bug was not discovered before because we were mainly using DisjunctionConstraint to check things like (y1 >= y2) or (y3 >= y2)... on the output variables.
 
I have created a PR #608 to fix the issue.
