### ISSUE TITLE
Marabou.read_onnx() seems to not recognize outputVars properly

### ISSUE THREAD

**Issue by Peipi98** [NeuralNetworkVerification/Marabou#664]
Hello,
I'm using the pip release of maraboupy and I'm facing the following issue.
I've exported a pytorch model with onnx following [this](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html), but when I use Marabou.read_onnx() it seems to not properly recognizing the output layer.
If you take a look into the following screenshot, you can see that in the varmap the outputVars are the same as the first hidden layer, and it's not supposed to be like that.

I've also tried with mnist_10_layer.nnet from [Prophecy](https://github.com/safednn-nasa/Prophecy/tree/master) and it seems to be correct with Marabou.read_nnet().

![image](https://github.com/NeuralNetworkVerification/Marabou/assets/39802340/d779d849-3351-47f7-953d-413a096610e8)

**Comment by Peipi98** [comment]
I've found that there is a variable called `reindexOutputVars` specified in the [official documentation](https://neuralnetworkverification.github.io/Marabou/API/4_MarabouNetworkONNX.html) which is responsible of the reassignment of the `outputVars` and its default value is `True`, so every time assign as output the same varMap indexes of the first hidden layer:
![image](https://github.com/NeuralNetworkVerification/Marabou/assets/39802340/89854c8f-432e-4fec-b815-3a9aba5d8612)
![image](https://github.com/NeuralNetworkVerification/Marabou/assets/39802340/8aee8fe3-55de-48a3-a82e-304063912a1d)

My suggestion is to specify this variable and make its meaning clearer. Hope this could be useful!

**Comment by wu-haoze** [comment]
Hi @Peipi98 , what you described is quite weird. If you use Marabou.read_onnx(), I would expect the outputVars to be 784-- 793 because reindexOutputVars is True by default. But I would also expect the first hidden layer to start from 794 and not over-lap with the output variable. Would you mind share the command (and ideally also the network) that you used that trigger this error? 

At the mean time, yes, I think it's a good idea to augment the documentation. Created a PR (#676) for that.
