### ISSUE TITLE
Upgrade CMake to 3.16+

### ISSUE THREAD

**Issue by MatthewDaggitt** [NeuralNetworkVerification/Marabou#722]
Marabou currently requires CMake 2.8.12.2 to build, which is over 5 years old now. We have Vehicle users who are struggling to install Marabou on various clusters etc. because their allowed version of CMake is too new (e.g. they need 3.16+).

The current verison of CMake is 3.28+...

**Comment by wu-haoze** [comment]
We do require cmake version 3.16+ https://github.com/NeuralNetworkVerification/Marabou/blob/f686c6bd99db76ffc3c148001e47d05095d2e8a3/CMakeLists.txt#L1

I have been using cmake 3.22 locally and our CI seems to be using that version as well. So I suspect the compilation issue is not due to cmake version being too new on their clusters.

**Comment by MatthewDaggitt** [comment]
Ah sorry, I got confused about the bug report. The cluster needed 2.8.12.2. So closing.
