### ISSUE TITLE
Conditional input in verification property

### ISSUE THREAD

**Issue by AWbosman** [NeuralNetworkVerification/Marabou#785]
Dear authors, 

I am interested in verifying a property where the change a certain input variable can make is dependent on another. 
In a comment on an issue @MatthewDaggitt gave an example ( x0 +x1 <=1) and I was wondering whether this kind of property is currently supported by Marabou as I have not seen any examples of this. 

_Originally posted by @MatthewDaggitt in https://github.com/NeuralNetworkVerification/Marabou/issues/490#issuecomment-985397152_

**Comment by wu-haoze** [comment]
Hi @AWbosman , Marabou supports general linear constraints over input variables. I usually prefer using the Python API: https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/examples/7_PythonicAPI.py

Marabou also now supports VNN_LIB format, which also can take constraints like that.

**Comment by wu-haoze** [comment]
@AWbosman , this is the right way to use it on the command line. `./Marabou --help` will show the command line options, including runtime.

The long running time could be due to the sub-optimal implementation of the C++ onnx parser (#754 ) which we are trying to fix. For now, please use the Python API if you want to parse a ONNX network.

**Comment by wu-haoze** [comment]
Closing the issue due to inactivity. Feel free to re-open if needed.
