### ISSUE TITLE
Error during Marabou build

### ISSUE THREAD

**Issue by phoenixbirdashes** [NeuralNetworkVerification/Marabou#801]
After using the following commands:

```
mkdir build
cd build
cmake ../
cmake --build ./
```

the following error is received:
.
.
.
11/76 Test #13: Test_InputQuery ............................    Passed    0.15 sec
           Start 15: Test_LeakyReluConstraint
12/76 Test #15: Test_LeakyReluConstraint ...........   Passed    0.08 sec
           Start 16: Test_MaxConstraint
Killed
gmake[2]: *** [CMakeFiles/build-tests.dir/build.make:70: build-tests] Error 137
gmake[1]: *** [CMakeFiles/Makefile2:813: CMakeFiles/build-tests.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2

![Screenshot 2024-04-18 220653](https://github.com/NeuralNetworkVerification/Marabou/assets/167457592/a5357b54-1ef2-48df-a082-dc22f2bab1da)

**Comment by phoenixbirdashes** [comment]
@wu-haoze,
1. The test were "Killed" after hanging for a while.
2. The test gets killed at different test cases each time when build, so I don't think a particular test case is the issue.
![Screenshot 2024-04-19 210549](https://github.com/NeuralNetworkVerification/Marabou/assets/167457592/443aa947-7580-4d80-abda-62b4277e041c)

**Comment by phoenixbirdashes** [comment]
> Just in case you're not aware, Marabou is available on pypi, `pip3 install maraboupy`. So it's worth trying that before building from scratch.

@wu-haoze As part of my project I am actually trying to extract the equations that gets generated for the DNN we give as Input from the Marabou Files, I am not sure if it can be done via the Python Interface.

**Comment by wu-haoze** [comment]
Hi, if the test hangs non-deterministically, but each individual test passes, my guess is that marabou is already successfully built. I’ve noticed that on resource constrained machines (not sure if your machine fits this description), ctest can hang for some reason. This is something we need to look into. To turn off automatically running unit test, replace “cmake ..” with “cmake .. -DRUN_UNIT_TEST=OFF”

Probably worth removing build/ and start from scratch (should be fairly quick since the downloaded/installed dependency won’t be removed).

With the pip package, yes I think if you’re passing in a network in onnx format and want to examine the encoding of the network, you could do it via the python API.

 https://github.com/NeuralNetworkVerification/Marabou/blob/3c8e1054ff10d4371525ff1e7e15f18430a2b6d2/maraboupy/examples/2_ONNXExample.py#L37

The network object (which is a subclass ofMaraboupy/parser/InputQueryBuilder.py)
generated by this command contains the information you need.

Andrew


在 2024年4月19日，08:40，



phoenixbirdashes ***@***.***> 写道：

﻿

Just in case you're not aware, Marabou is available on pypi, pip3 install maraboupy. So it's worth trying that before building from scratch.

@wu-haoze<https://github.com/wu-haoze> As part of my project I am actually trying to extract the equations that gets generated for the DNN we give as Input from the Marabou Files, I am not sure if it can be done via the Python Interface.

**Comment by phoenixbirdashes** [comment]
Hi,

Thanks for your reply, The "cmake .. -DRUN_UNIT_TEST=OFF" worked.

I am actually trying to run Marabou in a VirtualBox Ubuntu Environment.

**Comment by wu-haoze** [comment]
Closing the issue since it seems resolved. Feel free to re-open if needed.
